### PR TITLE
Job History Search - Advanced

### PR DESCRIPTION
**Pull request by lucanos**
The Job History Search has been expanded to provide both historic and current situational awareness when viewing a job.

History performs the following:
1. Performs search by street name & suburb (Beacon limits search to first 30 characters)
1. Walks through results
1. Categorises into four sections:
    - Exact Match: Address is 100% the same
    - Partial Match: Street Number matches, but looks like a Townhouse, Battleaxe or Apartment (ie if at Street Number 10, will match 10A, 10B, etc.)
    - Neighbouring Address: Street Number is +/-2 (ie if at Street Number 17, will match 15, 15A, etc.)
    - Street Match: Does not satisfy any of the above

Some minor rearrangement of the table was needed for this, as some matches now need to show address details.

Also utilised `moment()` to produce relative timestamps (hover for absolute time).

### CODE REVIEW

**Comment by lucanos** [comment]
17 Roland Avenue - https://trainbeacon.ses.nsw.gov.au/Jobs/6010

Neighbour matches for 15 and 15A.

screen shot 2016-02-08 at 4 18 05 am

**Comment by lucanos** [comment]
15 Roland Avenue - https://trainbeacon.ses.nsw.gov.au/Jobs/6009

Partial Address Match for 15A
Neighbour Match for 17

screen shot 2016-02-08 at 4 22 22 am

**Comment by lucanos** [comment]
15A Roland Avenue - https://trainbeacon.ses.nsw.gov.au/Jobs/6008

Partial Match for 15
Neighbour Match for 17

screen shot 2016-02-08 at 4 24 26 am

**Comment by lucanos** [comment]
11 Roland Ave - https://trainbeacon.ses.nsw.gov.au/Jobs/6007

Street Match for 10 and 12. No Neighbour match as odds/evens (they don't always align reliably).

screen shot 2016-02-08 at 4 25 56 am

**Comment by lucanos** [comment]
12 Roland Ave - https://trainbeacon.ses.nsw.gov.au/Jobs/6006

Neighbour match for 10.
Street match for 11.

screen shot 2016-02-08 at 4 27 37 am

**Comment by lucanos** [comment]
10 Roland Ave - https://trainbeacon.ses.nsw.gov.au/Jobs/6005

Neighbour match for 12.

screen shot 2016-02-08 at 4 29 35 am

**Comment by lucanos** [comment]
Ideas I am considering:

- Hiding Complete and Finalised Jobs for Street (with an indicator/toggle in the "Same Street" - "x Complete, y Finalised" which allows them to be displayed on demand)
- Sleeping...

**Comment by OSPFNeighbour** [comment]
possibly look at having exact address as 12 months, but same street as a much shorter time window like a week. knowing someone down the road has a branch down from last year isnt super relative . or as you said showing only open would be better

**Pull request merged**
