### PR TITLE
Job View - Job History - Layout Iteration

### PR DESCRIPTION
**Pull request by lucanos**
- Based on Tim's grouping and basic style
- Nested `<fieldset>`s for job groups
- Jobs older than 2 weeks, for Same Street, are hidden (unless the Job Status is "New", "Acknowledged", "Tasked" or "Referred")
- Hidden jobs can be toggled to visible

### CODE REVIEW

**Comment by lucanos** [comment]
https://trainbeacon.ses.nsw.gov.au/Jobs/6009

screen shot 2016-02-10 at 5 28 39 pm
screen shot 2016-02-10 at 5 28 29 pm
screen shot 2016-02-10 at 5 28 17 pm

**Comment by lucanos** [comment]
https://trainbeacon.ses.nsw.gov.au/Jobs/5745 - One Previous Job and Address, plus One in Street

screen shot 2016-02-10 at 6 22 23 pm
screen shot 2016-02-10 at 6 22 30 pm

**Comment by lucanos** [comment]
https://trainbeacon.ses.nsw.gov.au/Jobs/6010
- None at Same Address
- None at Partial Address Match
- Two at Neighbouring Addresses (including Partial Address)
- Multiple on Street

screen shot 2016-02-10 at 6 29 43 pm
screen shot 2016-02-10 at 6 29 56 pm

Toggled to show Old Jobs
screen shot 2016-02-10 at 6 30 06 pm

**Comment by lucanos** [comment]
https://trainbeacon.ses.nsw.gov.au/Jobs/5498
- None at Same Address
- None at Partial Address Match
- None at Neighbouring Address
- Multiple in Same Street

screen shot 2016-02-10 at 6 35 49 pm
screen shot 2016-02-10 at 6 36 01 pm

Toggled to show Old Jobs
screen shot 2016-02-10 at 6 36 11 pm

**Comment by OSPFNeighbour** [comment]
Sexy

**Comment by sdunster** [comment]
Tests were super useful for performing this merge - thanks.
Closed by cfdf5b81c678e4b741dcdd112fee6943e95f9a8b.

**Pull request closed without merging**
