### PR TITLE
Add lighthouse layers to the tasking map

### PR DESCRIPTION
**Pull request by tmyroadctfig**
I want to add the team positions to the tasking screen map, so this is the first step: starting to tease out some of the common code.

I did a quick smoke test of most things and they seemed to be working still.

### CODE REVIEW

**Comment by tmyroadctfig** [comment]
The review isn't ideal... this mostly turned into a cut & paste exercise. The biggest change is that I wrapped up the content side code into a class. I tried to do the same for the inject side, but it was a far larger task, so I left it for now.

**Comment by OSPFNeighbour** [comment]
Are you finally going to show tasked as well as onroute/site/off :P our flood desk would love to see tasked.

**Comment by tmyroadctfig** [comment]
I'm not sure how that would work. The goal here is for this to be a poor-man's AVL substitute, i.e. to give ops some rough ideal of where the team is/is-going, or just-left-from. If you mark the team down to every job it's tasked against, it might be a bit unclear where they are.

**Comment by OSPFNeighbour** [comment]
But when you go to task a job, knowing which jobs are tasked to who would
be helpful.

**Comment by OSPFNeighbour** [comment]
Happy to land but it conflicts now. any chance you can refactor?

**Pull request merged**
